
## Review accompanying files for output generated by this code

## Load all relevant packages

library(caret)
library(rpart)  ## contains the classifier we will be using
library(rpart.plot)
library(RColorBrewer)
library(rattle)   ## contains functions for graphical plotting that we will be using in the application.  

## Download data files and save locally. Set relevant working directory in R
## Load Test and Train files provided for the assignment. 
## Remove features or columns with sparse data from both files. They won't add to the quality of the model,
## they may skew the results or increase computational complexity unnecessarily.
  
  
TrainingFile <-  read.csv("MLQuizTraining.csv", na.strings=c("NA","#DIV/0!",""))
TrainingFile <- TrainingFile[,colSums(is.na(TrainingFile)) == 0]
TestingFile <- read.csv("MLQuizTesting.csv", na.strings=c("NA","#DIV/0!",""))
TestingFile <- TestingFile[,colSums(is.na(TestingFile)) == 0]


## Split the training file  provided for the exercise into training and validation sets
## Seed and then randomly assign 70% to the training set and 30% to the validation set
## The 20 samples in the testing file will be used separatey as a standalone final testing set

set.seed(787878)
inTrain <- createDataPartition(y=TrainingFile$classe, p=0.7, list=FALSE)
TrainingSet <- TrainingFile[inTrain, ] 
ValidationSet <- TrainingFile[-inTrain, ]
TestingSet <- TestingFile
dim(TrainingSet); dim(ValidationSet); dim(TestingSet)

## conduct exploratory analysis of the data. 
## There are several columns that don't appeat to be relevant to the model building. 
## The first column is the sample index, followed by user name, date and time stamps, etc. 
## Remove columns 1-7 as they don't contribute to the model from the Training Set, Validation set and Testing set

TrainingSet   <-TrainingSet[,-c(1:7)]
ValidationSetcolnames <- colnames(TrainingSet)
ValidationSet <- ValidationSet[ValidationSetcolnames]
TestingSet   <-TestingSet[,-c(1:7)]
dim(TrainingSet) ; dim(ValidationSet); dim(TestingSet)

## Build model for output classe againt all features in the data set
modFitPass1 <- rpart(classe ~ ., data=TrainingSet, method="class")

## view tree
fancyRpartPlot(modFitPass1)

## Predict using validation set created from training file for the assignment
predictionsPass1 <- predict(modFitPass1, ValidationSet, type = "class")

## Confusion Matrix
confusionMatrix(predictionsPass1, ValidationSet$classe)

## Final prediction
print(predictPass2 <- predict(modFitPass1, TestingSet,type="class"))
